apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goalixa-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: goalixa
spec:
  project: default
  source:
    repoURL: https://github.com/goalixa/goalixa-BFF.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: goalixa-bff
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
